CREATE TABLE IF NOT EXISTS CAMPAIGN (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(50),
	TEAM_ID int,
	START_DATE timestamp,
	EXPIRY_DATE timestamp
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS PARTNER (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(50),
	EMAIL varchar(50),
	BIRTH_DATE timestamp,
	TEAM_ID int
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `TEAM` (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(50)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS PARTNER_CAMPAIGN (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PARTNER_ID int,
	CAMPAIGN_ID int
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
